### ISSUE TITLE
移动端开发常见问题

### ISSUE THREAD

**Issue by yinjikai** [yinjikai/blog#1]
#### ios 滚动不流畅
在滚动元素添加
```css
overflow-y: auto;
-webkit-overflow-scrolling : touch;
```
#### 取消ios 点击反馈样式
在父级添加以下样式解决
```css
-webkit-tap-highlight-color: rgba(0, 0, 0, 0);
```
#### ios输入框不回弹问题
通过在focus，blur时添加时间监听处理页面滚动来解决
```js
//解决ios页面不回弹问题
export const solveKickBack = (ele) => {
  if (ele && typeof ele.addEventListener === 'function') {
    let v = 0;
    ele.addEventListener(
      'focus',
      function() {
        v = window.pageYOffset;
      },
      false
    );
    ele.addEventListener(
      'blur',
      function() {
        window.scrollTo(0, v);
      },
      false
    );
  }
};
```

**Comment by yinjikai** [comment]
#### mac指定模拟器版本

[参考链接]("https://www.jianshu.com/p/c5ad2e2be367")

#### flex-basis在低版本safari会导致元素高度为0

#### box-shadow绘制0.5px边框在ios有兼容问题，需要使用border方案代替

#### 绘制0.5px边框

```css
	::after{
		position: absolute;
        top: 0;
        left: 0;
        box-sizing: border-box;
        width: 200%;
        height: 200%;
        border: 3px solid currentColor;
        border-radius: 50%;
        transform: scale(0.5, 0.5);
        transform-origin: 0 0;
        content: '';
	}
```
